### ISSUE TITLE
About the data fetch issue

### ISSUE THREAD

**Issue by jx-aoraki** [HarukaMa/aleo-explorer#14]
Hi, I tried to run the Aleo Explorer on my local yesterday, but it seems the data fetch is not quite stable. I know the explorer using the P2P to index the data, but after indexing around 100 blocks, the node connection is always lost. Is it the node issue or the explorer is in an unstable state? I ask because I found the explorer UI is also broken if I already have some data in the DB.

BTW, just curious to know why the project using P2P to index data instead of RPC?

**Comment by HarukaMa** [comment]
Mainly because the network has changed a lot and I'm still in the progress of updating the code to support that. If my instance is not online, most probably you won't be able to use it without encountering many issues.

The explorer used p2p protocol as there was new block broadcasting and the explorer can immediately pick up new blocks instead of having to poll the API. Apparently we lost that advantage now, but I don't really want to write another set of ser/de for everything.

Also, as my explorer had a working interpreter for aleo instructions, I would need to parse the binary `Program` object anyway. It's a lot easier than writing a text parser from scratch. While you can use snarkVM to parse the program, you will get a binary stream back anyway, unless you are ready to bridge every small data type across python and rust.

**Comment by jx-aoraki** [comment]
@HarukaMa thx for your explanation.

**Comment by HarukaMa** [comment]
assumed solved for now

not that the explorer is working though
