### ISSUE TITLE
When P2P_BLOCK_BATCH_SIZE is greater than 1, running results in an error.

### ISSUE THREAD

**Issue by 60ke** [HarukaMa/aleo-explorer#19]
The error is as follows:
```bash
Arguments: ('ProtocolViolation',)
Application startup failed. Exiting.
Traceback (most recent call last):
  File "node.py", line 70, in worker
    size = await self.reader.readexactly(4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 730, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes
```
P2P_BLOCK_BATCH_SIZE=1, it's ok

**Comment by HarukaMa** [comment]
Modify snarkOS if you want to use any value greater than 1.

snarkOS might change the default limit to 5 later: https://github.com/AleoHQ/snarkOS/pull/3101

**Comment by howardwu** [comment]
To provide some more context, setting to 5 blocks (from 1 block) would improve sync times, however if a range of blocks contain several large transactions, this could cause a spillover in the buffer codec when transmitting the blocks because the blocks exceed the buffer capacity. The side effect here is that this would break syncing.
