### ISSUE TITLE
SolutionTransmissionID、TransactionTransmissionID error

### ISSUE THREAD

**Issue by mumu714** [HarukaMa/aleo-explorer#38]
SolutionTransmissionID(id_=SolutionID.loads(tid["commitment"]))
TransactionTransmissionID(id_=TransactionID.loads(tid["transaction_id"]))
Missing "checksum" important parameter

**Comment by HarukaMa** [comment]
I'm surprised this is not causing errors on my instance. Fixed in https://github.com/HarukaMa/aleo-explorer/commit/a4a1bfcb3650ebbdfdb4476a202abba2ca7f7215 by adding placeholder value since I don't really care about the actual checksum value (this explorer is intentionally not keeping full block data, especially the dag part).
You will have to adjust things if you want to save those values.
